//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruby.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ruby.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultAddEmpBtnTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultAddEmpBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultAddRoleBtnTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultAddRoleBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultAdressBoxTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultAdressBoxTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultAuthCodeBoxTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultAuthCodeBoxTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultDateBoxTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultDateBoxTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultEditEmpBtnTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultEditEmpBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultGenderFemaleTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultGenderFemaleTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultGenderMaleTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultGenderMaleTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultGenderOtherTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultGenderOtherTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultGendertBoxTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultGendertBoxTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultMailBoxTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultMailBoxTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultNameBoxTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultNameBoxTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultPhoneBoxTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultPhoneBoxTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultRemEmpBtnTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultRemEmpBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultRemoveRoleBtnTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultRemoveRoleBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultRoleBoxTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultRoleBoxTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultRoleNameTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultRoleNameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_DefaultSurnameBoxTxt {
            get {
                return ResourceManager.GetString("EmployeeEditor_DefaultSurnameBoxTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_PermissionContent00 {
            get {
                return ResourceManager.GetString("EmployeeEditor_PermissionContent00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_PermissionContent01 {
            get {
                return ResourceManager.GetString("EmployeeEditor_PermissionContent01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_PermissionContent02 {
            get {
                return ResourceManager.GetString("EmployeeEditor_PermissionContent02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_PermissionContent03 {
            get {
                return ResourceManager.GetString("EmployeeEditor_PermissionContent03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_PermissionContent04 {
            get {
                return ResourceManager.GetString("EmployeeEditor_PermissionContent04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_PermissionContent05 {
            get {
                return ResourceManager.GetString("EmployeeEditor_PermissionContent05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_PermissionContent06 {
            get {
                return ResourceManager.GetString("EmployeeEditor_PermissionContent06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_PermissionContent07 {
            get {
                return ResourceManager.GetString("EmployeeEditor_PermissionContent07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_PermissionContent08 {
            get {
                return ResourceManager.GetString("EmployeeEditor_PermissionContent08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_PermissionContent09 {
            get {
                return ResourceManager.GetString("EmployeeEditor_PermissionContent09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_PermissionContent10 {
            get {
                return ResourceManager.GetString("EmployeeEditor_PermissionContent10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_PermissionContent11 {
            get {
                return ResourceManager.GetString("EmployeeEditor_PermissionContent11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_PermissionContent12 {
            get {
                return ResourceManager.GetString("EmployeeEditor_PermissionContent12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_PermissionContent13 {
            get {
                return ResourceManager.GetString("EmployeeEditor_PermissionContent13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EmployeeEditor_PermissionContent14 {
            get {
                return ResourceManager.GetString("EmployeeEditor_PermissionContent14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Entity_Account {
            get {
                return ResourceManager.GetString("Entity_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Entity_Category {
            get {
                return ResourceManager.GetString("Entity_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Entity_Employee {
            get {
                return ResourceManager.GetString("Entity_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Entity_History {
            get {
                return ResourceManager.GetString("Entity_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Entity_Product {
            get {
                return ResourceManager.GetString("Entity_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Entity_Role {
            get {
                return ResourceManager.GetString("Entity_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Entity_Scence {
            get {
                return ResourceManager.GetString("Entity_Scence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Entity_Serving {
            get {
                return ResourceManager.GetString("Entity_Serving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Entity_Table {
            get {
                return ResourceManager.GetString("Entity_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Entity_Ticket {
            get {
                return ResourceManager.GetString("Entity_Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string ERROR_FailToCreateEmpMessage {
            get {
                return ResourceManager.GetString("ERROR_FailToCreateEmpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string ERROR_FailToCreateTableMessage {
            get {
                return ResourceManager.GetString("ERROR_FailToCreateTableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string ERROR_LoginError1 {
            get {
                return ResourceManager.GetString("ERROR_LoginError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string ERROR_LoginError2 {
            get {
                return ResourceManager.GetString("ERROR_LoginError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EXC_FailToChangeEmp {
            get {
                return ResourceManager.GetString("EXC_FailToChangeEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EXC_FailToConnectDatabaseMessage {
            get {
                return ResourceManager.GetString("EXC_FailToConnectDatabaseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EXC_FailToConnectDatabaseTitle {
            get {
                return ResourceManager.GetString("EXC_FailToConnectDatabaseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EXC_FailToCreateEmp {
            get {
                return ResourceManager.GetString("EXC_FailToCreateEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EXC_FailToCreateTable {
            get {
                return ResourceManager.GetString("EXC_FailToCreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string EXC_FailToEditTable {
            get {
                return ResourceManager.GetString("EXC_FailToEditTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string HistoryManager_ActiveTables {
            get {
                return ResourceManager.GetString("HistoryManager_ActiveTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string HistoryManager_CriteriaCleanerBtnTxt {
            get {
                return ResourceManager.GetString("HistoryManager_CriteriaCleanerBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string HistoryManager_DefaultSelectEmployeeTxt {
            get {
                return ResourceManager.GetString("HistoryManager_DefaultSelectEmployeeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string HistoryManager_DefaultSelectProductTxt {
            get {
                return ResourceManager.GetString("HistoryManager_DefaultSelectProductTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string HistoryManager_DefaultSelectTableTxt {
            get {
                return ResourceManager.GetString("HistoryManager_DefaultSelectTableTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string HistoryManager_TotalSalesDefaultText {
            get {
                return ResourceManager.GetString("HistoryManager_TotalSalesDefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string HistoryManager_TotalSoldProducts {
            get {
                return ResourceManager.GetString("HistoryManager_TotalSoldProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string LoginPage_LoginBtnText {
            get {
                return ResourceManager.GetString("LoginPage_LoginBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string LoginPage_LoginError1 {
            get {
                return ResourceManager.GetString("LoginPage_LoginError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string LoginPage_LoginError2 {
            get {
                return ResourceManager.GetString("LoginPage_LoginError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string LoginPage_LoginTextBoxTxt {
            get {
                return ResourceManager.GetString("LoginPage_LoginTextBoxTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string LoginPage_LoginTitle {
            get {
                return ResourceManager.GetString("LoginPage_LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MainPage_EmptyScenceTxt {
            get {
                return ResourceManager.GetString("MainPage_EmptyScenceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MainPage_ExitMessage {
            get {
                return ResourceManager.GetString("MainPage_ExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MainPage_ExitTitle {
            get {
                return ResourceManager.GetString("MainPage_ExitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MainPage_NoScences {
            get {
                return ResourceManager.GetString("MainPage_NoScences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MainPage_NoTables {
            get {
                return ResourceManager.GetString("MainPage_NoTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MainPage_QuickAddTableBtnTxt {
            get {
                return ResourceManager.GetString("MainPage_QuickAddTableBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MainPage_QuickAddTableLabelTxt {
            get {
                return ResourceManager.GetString("MainPage_QuickAddTableLabelTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_AlreadyExistsMessage {
            get {
                return ResourceManager.GetString("MB_AlreadyExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_AlreadyExistsTitle {
            get {
                return ResourceManager.GetString("MB_AlreadyExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_CreateCopyOfMessage {
            get {
                return ResourceManager.GetString("MB_CreateCopyOfMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_CreateCopyOfTitle {
            get {
                return ResourceManager.GetString("MB_CreateCopyOfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_EmpNotFoundMessage {
            get {
                return ResourceManager.GetString("MB_EmpNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_EmpNotFoundTitle {
            get {
                return ResourceManager.GetString("MB_EmpNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_ErrorAdissionMessage {
            get {
                return ResourceManager.GetString("MB_ErrorAdissionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_ErrorAdissionTitle {
            get {
                return ResourceManager.GetString("MB_ErrorAdissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_FailedConnection {
            get {
                return ResourceManager.GetString("MB_FailedConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_FailedConnectionTitle {
            get {
                return ResourceManager.GetString("MB_FailedConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_FillRequiredAreasMessage {
            get {
                return ResourceManager.GetString("MB_FillRequiredAreasMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_FillRequiredAreasTitle {
            get {
                return ResourceManager.GetString("MB_FillRequiredAreasTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_ItemIsNotSelectedMessage {
            get {
                return ResourceManager.GetString("MB_ItemIsNotSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_ItemIsNotSelectedTitle {
            get {
                return ResourceManager.GetString("MB_ItemIsNotSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string MB_LockedTableMessage {
            get {
                return ResourceManager.GetString("MB_LockedTableMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_LockedTableTitle {
            get {
                return ResourceManager.GetString("MB_LockedTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_NO {
            get {
                return ResourceManager.GetString("MB_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_NoPermissionToProcessMessage {
            get {
                return ResourceManager.GetString("MB_NoPermissionToProcessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_NoPermissionToProcessTitle {
            get {
                return ResourceManager.GetString("MB_NoPermissionToProcessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_NoServingMessage {
            get {
                return ResourceManager.GetString("MB_NoServingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_NoServingTitle {
            get {
                return ResourceManager.GetString("MB_NoServingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_NotSavedMessage {
            get {
                return ResourceManager.GetString("MB_NotSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_NotSavedTitle {
            get {
                return ResourceManager.GetString("MB_NotSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_NumberedRequiredAreaMessage {
            get {
                return ResourceManager.GetString("MB_NumberedRequiredAreaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_NumberedRequiredAreaTitle {
            get {
                return ResourceManager.GetString("MB_NumberedRequiredAreaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_OKAY {
            get {
                return ResourceManager.GetString("MB_OKAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_RestartNeededMessage {
            get {
                return ResourceManager.GetString("MB_RestartNeededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_RestartNeededTitle {
            get {
                return ResourceManager.GetString("MB_RestartNeededTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_RoleHasEmployeesMessage {
            get {
                return ResourceManager.GetString("MB_RoleHasEmployeesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_RoleHasEmployeesTitle {
            get {
                return ResourceManager.GetString("MB_RoleHasEmployeesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_RoleNotFoundMessage {
            get {
                return ResourceManager.GetString("MB_RoleNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_RoleNotFoundTitle {
            get {
                return ResourceManager.GetString("MB_RoleNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_RoleNotSelectedMessage {
            get {
                return ResourceManager.GetString("MB_RoleNotSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_RoleNotSelectedTitle {
            get {
                return ResourceManager.GetString("MB_RoleNotSelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_SettingsChangedMessage {
            get {
                return ResourceManager.GetString("MB_SettingsChangedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_SettingsChangedTitle {
            get {
                return ResourceManager.GetString("MB_SettingsChangedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_SuccessfullConnection {
            get {
                return ResourceManager.GetString("MB_SuccessfullConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_SuccessfullConnectionTitle {
            get {
                return ResourceManager.GetString("MB_SuccessfullConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_SureToDeleteMessage {
            get {
                return ResourceManager.GetString("MB_SureToDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_SureToDeleteSubitemsMessage {
            get {
                return ResourceManager.GetString("MB_SureToDeleteSubitemsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_SureToDeleteTitle {
            get {
                return ResourceManager.GetString("MB_SureToDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_SureToEditMessage {
            get {
                return ResourceManager.GetString("MB_SureToEditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_SureToEditTitle {
            get {
                return ResourceManager.GetString("MB_SureToEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string MB_YES {
            get {
                return ResourceManager.GetString("MB_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Navigator_EmployeeEDesc {
            get {
                return ResourceManager.GetString("Navigator_EmployeeEDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Navigator_EmployeeETitle {
            get {
                return ResourceManager.GetString("Navigator_EmployeeETitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Navigator_HistoryMDesc {
            get {
                return ResourceManager.GetString("Navigator_HistoryMDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Navigator_HistoryMTitle {
            get {
                return ResourceManager.GetString("Navigator_HistoryMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Navigator_ProductEDesc {
            get {
                return ResourceManager.GetString("Navigator_ProductEDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Navigator_ProductETitle {
            get {
                return ResourceManager.GetString("Navigator_ProductETitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Navigator_SettingsPTitle {
            get {
                return ResourceManager.GetString("Navigator_SettingsPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Navigator_TableEDesc {
            get {
                return ResourceManager.GetString("Navigator_TableEDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string Navigator_TableETitle {
            get {
                return ResourceManager.GetString("Navigator_TableETitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string NOTIF_AccessedToScreen {
            get {
                return ResourceManager.GetString("NOTIF_AccessedToScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string NOTIF_AcessedToTable {
            get {
                return ResourceManager.GetString("NOTIF_AcessedToTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string NOTIF_ClosedApp {
            get {
                return ResourceManager.GetString("NOTIF_ClosedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string NOTIF_OpenedApp {
            get {
                return ResourceManager.GetString("NOTIF_OpenedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string NOTIF_TableChanged {
            get {
                return ResourceManager.GetString("NOTIF_TableChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string NOTIF_TicketDeleted {
            get {
                return ResourceManager.GetString("NOTIF_TicketDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string PROCESS_CategoryCreated {
            get {
                return ResourceManager.GetString("PROCESS_CategoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string PROCESS_DBConnection {
            get {
                return ResourceManager.GetString("PROCESS_DBConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string PROCESS_EmpChanged {
            get {
                return ResourceManager.GetString("PROCESS_EmpChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string PROCESS_EmpCreated {
            get {
                return ResourceManager.GetString("PROCESS_EmpCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string PROCESS_EmpDeleted {
            get {
                return ResourceManager.GetString("PROCESS_EmpDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string PROCESS_ProductCategorySetted {
            get {
                return ResourceManager.GetString("PROCESS_ProductCategorySetted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string PROCESS_ProductCreated {
            get {
                return ResourceManager.GetString("PROCESS_ProductCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string PROCESS_ProductDeleted {
            get {
                return ResourceManager.GetString("PROCESS_ProductDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string PROCESS_RoleCreated {
            get {
                return ResourceManager.GetString("PROCESS_RoleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string PROCESS_RoleDeleted {
            get {
                return ResourceManager.GetString("PROCESS_RoleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string PROCESS_ScenceCreated {
            get {
                return ResourceManager.GetString("PROCESS_ScenceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string PROCESS_ScenceDeleted {
            get {
                return ResourceManager.GetString("PROCESS_ScenceDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string PROCESS_TableChanged {
            get {
                return ResourceManager.GetString("PROCESS_TableChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string PROCESS_TableCreated {
            get {
                return ResourceManager.GetString("PROCESS_TableCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string PROCESS_TableDeleted {
            get {
                return ResourceManager.GetString("PROCESS_TableDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string PROCESS_TicketCreated {
            get {
                return ResourceManager.GetString("PROCESS_TicketCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string ProductEditor_DefaultBarcodeTxt {
            get {
                return ResourceManager.GetString("ProductEditor_DefaultBarcodeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string ProductEditor_DefaultCategoryNameTxt {
            get {
                return ResourceManager.GetString("ProductEditor_DefaultCategoryNameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string ProductEditor_DefaultPriceTxt {
            get {
                return ResourceManager.GetString("ProductEditor_DefaultPriceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string ProductEditor_DefaultProductNameTxt {
            get {
                return ResourceManager.GetString("ProductEditor_DefaultProductNameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string ProductEditor_DefaultQuantityTxt {
            get {
                return ResourceManager.GetString("ProductEditor_DefaultQuantityTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string ProductEditor_DefaultRemBtnTxt {
            get {
                return ResourceManager.GetString("ProductEditor_DefaultRemBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string ProductEditor_DefaultSaveBtnTxt {
            get {
                return ResourceManager.GetString("ProductEditor_DefaultSaveBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string ProductEditor_DefaultServingTxt {
            get {
                return ResourceManager.GetString("ProductEditor_DefaultServingTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string ProductEditor_DefaultTaxTxt {
            get {
                return ResourceManager.GetString("ProductEditor_DefaultTaxTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultAdissionPageTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultAdissionPageTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultCheckConnectionBtnTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultCheckConnectionBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultConnectionStringTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultConnectionStringTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultDatabaseNameTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultDatabaseNameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultDatabaseSettingsTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultDatabaseSettingsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultDatabaseTypeTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultDatabaseTypeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultGeneralSettingsTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultGeneralSettingsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultHeightTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultHeightTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultLanguagrTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultLanguagrTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultMachineNameTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultMachineNameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultOrganizationNameTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultOrganizationNameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultOrganizationSettingsTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultOrganizationSettingsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultOrganizationTypeTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultOrganizationTypeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultPasswordTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultPasswordTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultServerNameTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultServerNameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultShowBtnOptionTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultShowBtnOptionTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultStartWithMachineTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultStartWithMachineTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultUserNameTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultUserNameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_DefaultWidthTxt {
            get {
                return ResourceManager.GetString("SettingsPage_DefaultWidthTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_ImportAdissionBtnTxt {
            get {
                return ResourceManager.GetString("SettingsPage_ImportAdissionBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SettingsPage_PrintSampleBtnTxt {
            get {
                return ResourceManager.GetString("SettingsPage_PrintSampleBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SetupPage_DefaultNextBtnTxt {
            get {
                return ResourceManager.GetString("SetupPage_DefaultNextBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SetupScreen_CompletedMessage {
            get {
                return ResourceManager.GetString("SetupScreen_CompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SetupScreen_DatabaseSettingsTitle {
            get {
                return ResourceManager.GetString("SetupScreen_DatabaseSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SetupScreen_EmployeeRequired {
            get {
                return ResourceManager.GetString("SetupScreen_EmployeeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SetupScreen_EnjoyService {
            get {
                return ResourceManager.GetString("SetupScreen_EnjoyService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SetupScreen_FirstEmployeesTitle {
            get {
                return ResourceManager.GetString("SetupScreen_FirstEmployeesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SetupScreen_GeneralSettingsTitle {
            get {
                return ResourceManager.GetString("SetupScreen_GeneralSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SetupScreen_NoAdminFound {
            get {
                return ResourceManager.GetString("SetupScreen_NoAdminFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SetupScreen_Purpose {
            get {
                return ResourceManager.GetString("SetupScreen_Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SetupScreen_Redirecting {
            get {
                return ResourceManager.GetString("SetupScreen_Redirecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SetupScreen_SettingSettigs {
            get {
                return ResourceManager.GetString("SetupScreen_SettingSettigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SetupScreen_SettingSettigsMessage {
            get {
                return ResourceManager.GetString("SetupScreen_SettingSettigsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string SetupScreen_WelcomeText {
            get {
                return ResourceManager.GetString("SetupScreen_WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TableEditor_DefaultAddScenceBtnTxt {
            get {
                return ResourceManager.GetString("TableEditor_DefaultAddScenceBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TableEditor_DefaultAdvancedColorsTxt {
            get {
                return ResourceManager.GetString("TableEditor_DefaultAdvancedColorsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TableEditor_DefaultCreateTableBtnTxt {
            get {
                return ResourceManager.GetString("TableEditor_DefaultCreateTableBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TableEditor_DefaultEditTableBtnTxt {
            get {
                return ResourceManager.GetString("TableEditor_DefaultEditTableBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TableEditor_DefaultEnabledCheckTxt {
            get {
                return ResourceManager.GetString("TableEditor_DefaultEnabledCheckTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TableEditor_DefaultLockCheckTxt {
            get {
                return ResourceManager.GetString("TableEditor_DefaultLockCheckTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TableEditor_DefaultRemoveScenceBtnTxt {
            get {
                return ResourceManager.GetString("TableEditor_DefaultRemoveScenceBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TableEditor_DefaultRemoveTableBtnTxt {
            get {
                return ResourceManager.GetString("TableEditor_DefaultRemoveTableBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TableEditor_DefaultReservableCheckTxt {
            get {
                return ResourceManager.GetString("TableEditor_DefaultReservableCheckTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TableEditor_DefaultScenceAdderTxt {
            get {
                return ResourceManager.GetString("TableEditor_DefaultScenceAdderTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TableEditor_DefaultStandardColorsTxt {
            get {
                return ResourceManager.GetString("TableEditor_DefaultStandardColorsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TableEditor_DefaultTableColorTxt {
            get {
                return ResourceManager.GetString("TableEditor_DefaultTableColorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TableEditor_DefaultTableMaxChairTxt {
            get {
                return ResourceManager.GetString("TableEditor_DefaultTableMaxChairTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TableEditor_DefaultTableNameTxt {
            get {
                return ResourceManager.GetString("TableEditor_DefaultTableNameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TableEditor_DefaultTableScenceTxt {
            get {
                return ResourceManager.GetString("TableEditor_DefaultTableScenceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TableEditor_DefaultTableTypeTxt {
            get {
                return ResourceManager.GetString("TableEditor_DefaultTableTypeTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TableEditor_EmptyScenceText {
            get {
                return ResourceManager.GetString("TableEditor_EmptyScenceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TicketPage_AddedItemToAccount {
            get {
                return ResourceManager.GetString("TicketPage_AddedItemToAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TicketPage_DefaultCashBtnTxt {
            get {
                return ResourceManager.GetString("TicketPage_DefaultCashBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TicketPage_DefaultChangeTableBtnTxt {
            get {
                return ResourceManager.GetString("TicketPage_DefaultChangeTableBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TicketPage_DefaultCloseTableBtnTxt {
            get {
                return ResourceManager.GetString("TicketPage_DefaultCloseTableBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TicketPage_DefaultCreditBtnTxt {
            get {
                return ResourceManager.GetString("TicketPage_DefaultCreditBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TicketPage_DefaultMenuListTxt {
            get {
                return ResourceManager.GetString("TicketPage_DefaultMenuListTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TicketPage_DefaultMultiplierBoxTxt {
            get {
                return ResourceManager.GetString("TicketPage_DefaultMultiplierBoxTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TicketPage_DefaultPriceBoxTxt {
            get {
                return ResourceManager.GetString("TicketPage_DefaultPriceBoxTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TicketPage_DefaultPrintTicketTxt {
            get {
                return ResourceManager.GetString("TicketPage_DefaultPrintTicketTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TicketPage_DefaultServingBoxTxt {
            get {
                return ResourceManager.GetString("TicketPage_DefaultServingBoxTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TicketPage_DefaultTableNameTxt {
            get {
                return ResourceManager.GetString("TicketPage_DefaultTableNameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TicketPage_DefaultTotalPriceTxt {
            get {
                return ResourceManager.GetString("TicketPage_DefaultTotalPriceTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TicketPage_DefaultTurnBackBtnTxt {
            get {
                return ResourceManager.GetString("TicketPage_DefaultTurnBackBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string TicketPage_RemovedItemFromAccount {
            get {
                return ResourceManager.GetString("TicketPage_RemovedItemFromAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string WARN_AddScenceNotif {
            get {
                return ResourceManager.GetString("WARN_AddScenceNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string WARN_AddTableNotif {
            get {
                return ResourceManager.GetString("WARN_AddTableNotif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NULL.
        /// </summary>
        public static string WARN_TableCanceled {
            get {
                return ResourceManager.GetString("WARN_TableCanceled", resourceCulture);
            }
        }
    }
}
